In [4]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor,Lambda

ds=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y:torch.zeros(10,dtype=torch.float).scatter_(0,torch.tensor(y),value=1))
)

In [2]:
torch.zeros(10,dtype=torch.float).scatter_(0,torch.tensor(1),value=1)

tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
torch.tensor(1)
input_image=torch.rand(3,28,28)

In [7]:
print(f"{input_image.size()}")

torch.Size([3, 28, 28])


In [9]:
from torch import nn
flattern=nn.Flatten()
flat_image=flattern(input_image)
print(flat_image.size())


torch.Size([3, 784])


In [10]:
layer1=nn.Linear(in_features=28*28,out_features=20)
hidden1=layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [11]:
print(f"Before ReLU:{hidden1} \n\n")
hidden1=nn.ReLU()(hidden1)
print(f"After ReLU:{hidden1}")

Before ReLU:tensor([[-0.2094, -0.0384,  0.2660,  0.0574,  0.4865, -0.3501, -0.4141, -0.3784,
         -0.0897,  0.1174, -0.1649,  0.6103,  0.8611, -0.1728,  0.3123, -0.4789,
         -0.0632,  0.2517, -0.7852, -0.3261],
        [-0.3276,  0.1557,  0.9369,  0.0686,  0.3971, -0.2184, -0.5135, -0.5442,
         -0.0227, -0.0805, -0.2419,  0.6618,  0.6380,  0.0608,  0.3582, -0.5822,
          0.2970,  0.2636, -0.7168, -0.0751],
        [-0.1281,  0.4012,  0.3575, -0.0680,  0.3042, -0.3125, -0.6948, -0.5237,
          0.1450,  0.1439, -0.2667,  0.4990,  0.7478, -0.2145,  0.4990, -0.4256,
          0.2469,  0.5350, -0.7432, -0.2749]], grad_fn=<AddmmBackward0>) 


After ReLU:tensor([[0.0000, 0.0000, 0.2660, 0.0574, 0.4865, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1174, 0.0000, 0.6103, 0.8611, 0.0000, 0.3123, 0.0000, 0.0000, 0.2517,
         0.0000, 0.0000],
        [0.0000, 0.1557, 0.9369, 0.0686, 0.3971, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.6618, 0.6380, 0.0608, 0.358

In [12]:
seq_modules=nn.Sequential(
    flattern,
    layer1,
    nn.ReLU(),
    nn.Linear(20,10)
)
input_image=torch.rand(3,28,28)
logits=seq_modules(input_image)

In [13]:
logits

tensor([[ 0.3686, -0.0575, -0.0359,  0.3938,  0.3020, -0.0484,  0.3736,  0.3380,
          0.2281,  0.1739],
        [ 0.3408, -0.1263,  0.1480,  0.2421,  0.1392,  0.0377,  0.3217,  0.2190,
          0.1461,  0.1167],
        [ 0.3038, -0.0989, -0.0086,  0.3743,  0.1091, -0.0092,  0.3116,  0.2652,
          0.1678,  0.1244]], grad_fn=<AddmmBackward0>)

In [14]:
softmax=nn.Softmax(dim=1)
pred_probab=softmax(logits)
pred_probab

tensor([[0.1162, 0.0759, 0.0775, 0.1192, 0.1087, 0.0766, 0.1168, 0.1127, 0.1010,
         0.0956],
        [0.1190, 0.0746, 0.0981, 0.1078, 0.0973, 0.0879, 0.1168, 0.1054, 0.0980,
         0.0951],
        [0.1149, 0.0768, 0.0840, 0.1233, 0.0945, 0.0840, 0.1158, 0.1105, 0.1003,
         0.0960]], grad_fn=<SoftmaxBackward0>)

In [15]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [16]:
model = NeuralNetwork().to("cpu")
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [17]:
for name,param in model.named_parameters():
    print(f"Layer:{name} | Size:{param.size()} | Values:{param[:2]} \n")

Layer:linear_relu_stack.0.weight | Size:torch.Size([512, 784]) | Values:tensor([[-0.0327, -0.0254, -0.0027,  ..., -0.0162,  0.0038, -0.0308],
        [-0.0057, -0.0252,  0.0248,  ..., -0.0306, -0.0327,  0.0018]],
       grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.0.bias | Size:torch.Size([512]) | Values:tensor([ 0.0018, -0.0232], grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.2.weight | Size:torch.Size([512, 512]) | Values:tensor([[-0.0392,  0.0065, -0.0272,  ..., -0.0282, -0.0252,  0.0208],
        [-0.0353, -0.0265, -0.0310,  ...,  0.0414, -0.0199,  0.0430]],
       grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.2.bias | Size:torch.Size([512]) | Values:tensor([-0.0183,  0.0174], grad_fn=<SliceBackward0>) 

Layer:linear_relu_stack.4.weight | Size:torch.Size([10, 512]) | Values:tensor([[ 0.0173, -0.0255, -0.0233,  ..., -0.0268,  0.0420,  0.0175],
        [-0.0078,  0.0356,  0.0364,  ..., -0.0411,  0.0172,  0.0187]],
       grad_fn=<SliceBackward0>) 

Layer:linear_relu